from pydantic import BaseModel


class LeagueConfig(BaseModel):
    key: str
    name: str
    league_id: str
    season: str
    num_teams: int
    roster_positions: list[str]
    faab: bool
    # Points per reception. Together with num_teams this decides which prebuilt
    # draft pool fits a league, since both drive ADP.
    ppr: float = 1.0
    friend_group: str = ""
    # True when the league is served by a pool built for a different league
    # shape, so the frontend can say the projections are approximate.
    approx_pool: bool = False


LEAGUES: dict[str, LeagueConfig] = {
    "miller_league_hs": LeagueConfig(
        key="miller_league_hs",
        name="Miller League",
        league_id="1315433135034355712",
        season="2026",
        num_teams=14,
        ppr=0.5,
        friend_group="high_school",
        roster_positions=["QB", "RB", "RB", "WR", "WR", "TE", "FLEX", "K", "DEF",
                           "BN", "BN", "BN", "BN", "BN"],
        faab=True,
    ),
    "maxxing_college": LeagueConfig(
        key="maxxing_college",
        name="FANTASYFOOTBALLMAXXING",
        league_id="1386491914559197184",
        season="2026",
        num_teams=10,
        ppr=1.0,
        friend_group="college",
        roster_positions=["QB", "RB", "RB", "WR", "WR", "TE", "FLEX", "FLEX", "K", "DEF",
                           "BN", "BN", "BN", "BN", "BN"],
        faab=False,
    ),
}

# The leagues above double as the registry of prebuilt draft pools: each has a
# data/pools/<key>.csv generated by ffb.nfldata.build for its (ppr, num_teams).
SLEEPER_USER_ID = "1125887731814576128"
SLEEPER_USERNAME = "lucaspedroferreira"
